name = "khomasi-notifications"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
FCM_PROJECT_ID = "khomasi-177f3"

# Run every 5 minutes - checks matches starting within 1 hour
[triggers]
crons = ["*/5 * * * *"]
