// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK5Zsil8FdYSvobQsyhxwOUj5opk2wegs',
    appId: '1:987654545846:web:3dc57227ac45c11ad76117',
    messagingSenderId: '987654545846',
    projectId: 'khomasi-177f3',
    authDomain: 'khomasi-177f3.firebaseapp.com',
    storageBucket: 'khomasi-177f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPBj3TisfN7TDzMLAayEBRLEW4EcaqSz0',
    appId: '1:987654545846:android:8cad4f8a6d386f4bd76117',
    messagingSenderId: '987654545846',
    projectId: 'khomasi-177f3',
    storageBucket: 'khomasi-177f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoWt8Z9CIX4t010OdJxqyUxdLBub6hHeM',
    appId: '1:987654545846:ios:91d23d7a350f3c5bd76117',
    messagingSenderId: '987654545846',
    projectId: 'khomasi-177f3',
    storageBucket: 'khomasi-177f3.firebasestorage.app',
    iosBundleId: 'com.example.khomasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoWt8Z9CIX4t010OdJxqyUxdLBub6hHeM',
    appId: '1:987654545846:ios:91d23d7a350f3c5bd76117',
    messagingSenderId: '987654545846',
    projectId: 'khomasi-177f3',
    storageBucket: 'khomasi-177f3.firebasestorage.app',
    iosBundleId: 'com.example.khomasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK5Zsil8FdYSvobQsyhxwOUj5opk2wegs',
    appId: '1:987654545846:web:d2a7869fd7750272d76117',
    messagingSenderId: '987654545846',
    projectId: 'khomasi-177f3',
    authDomain: 'khomasi-177f3.firebaseapp.com',
    storageBucket: 'khomasi-177f3.firebasestorage.app',
  );
}
